#CSC111 Computer Science II
#Lab 9 makefile
#Programmers: Adam Haertter & Yong Hang Lin
#Professor: Dr. Lee
#File Created: Oct 28, 2019
#File Updated: Oct 28, 2019

SOURCES = lab9.c
OBJECTS = lab9.o

CC = gcc
CFLAG = -g -Wall

Lab9: $(OBJECT)
	$(CC) $(CFLAGS) $(OBJECTS) -o lab9
