# CSC111 Computer Science II
# Lab 14: p585n6.c
# Programmers: Scott Bucher, Adam Haertter, Andrew Kress
# Professor: Dr. Lee
# Date Created: Nov 13, 2019
# Date Updated: Nov 17, 2019

#You press the tab key when you see [TAB] in the following makefile
SOURCES = p585n6.c                 #defines the sources
OBJECTS = p585n6.o                 #defines the objects

CC = gcc
CFLAGS = -g -Wall

Lab14: $(OBJECTS)                           #defines Lab14 build
	$(CC) $(CFLAGS) $(OBJECTS) -o p585n6
clean:                                         #defines clean build
	rm -fR *o p585n6
