#CSC111 Computer Science II
#Lab 12: makefile
#Programmers: Austin Sheppard
#Professor: Dr. Lee
#File Created: November 11th, 2019
#File Updated: November 11th, 2019

SOURCES = lab12.c 
OBJECTS = lab12.o
CC = gcc
CFLAGS = -g -Wall

Lab12: $(OBJECTS)
	$(CC) $(CFLAGS) $(OBJECTS) -o lab12
clean:
	rm -fR *o lab12
