#CSC111: Computer Science II
#Remind 2: readme
#Programmer: Adam Haertter & Andrew Kress
#Professor: Dr. Lee
#Date Created: 10/21/19
#Date Updated: 10/21/19

SOURCES = remindb.c
OBJECTS = remindb.o
CC = gcc
CFLAGS = -g -Wall

Inventory: $(OBJECTS)
	$(CC) $(FLAGS) $(OBJECTS) -o remindb
clean:
	rm -fR *o inventoryb

