#CSC111: Computer Science 2
#Maintains a parts database (linked list version)
#Programmer: Andrew Kress & Adam Haertter
#Professor: Dr. Lee
#Date Created: 10/21/19
#Date Modified: 10/21/19

SOURCES = inventoryb.c readline.c
OBJECTS = inventoryb.o readline.o
HEADERS = readline.h
CC = gcc
CFLAGS = -g -Wall

Inventory: $(OBJECTS)
	$(CC) $(FLAGS) $(OBJECTS) -o inventoryb
clean:
	rm -fR *o inventoryb
